//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 04:57:01 PM MSK 
//


package org.qubership.kafka.security.audit.history;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Java class for severityMap complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="severityMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SeverityNode" type="{}severityNode" maxOccurs="unbounded"
 * minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "severityMap", propOrder = {
    "severityNode"
})
public class SeverityMap {

  @XmlElement(name = "SeverityNode")
  protected List<SeverityNode> severityNode;

  /**
   * Gets the value of the severityNode property.
   *
   * <p>This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the severityNode property.
   *
   * <p>For example, to add a new item, do as follows:
   * <pre>
   *    getSeverityNode().add(newItem);
   * </pre>
   *
   *
   * <p>Objects of the following type(s) are allowed in the list
   * {@link SeverityNode }
   */
  public List<SeverityNode> getSeverityNode() {
    if (severityNode == null) {
      severityNode = new ArrayList<SeverityNode>();
    }
    return this.severityNode;
  }

}
