//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 04:57:01 PM MSK 
//


package org.qubership.kafka.security.audit.history;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Java class for severityNode complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="severityNode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="eventSignature" use="required" type="{http://www.w3.org/2001/XMLSchema}string"
 * />
 *       &lt;attribute name="severity" use="required" type="{http://www.w3.org/2001/XMLSchema}int"
 * />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "severityNode")
public class SeverityNode {

  @XmlAttribute(name = "eventSignature", required = true)
  protected String eventSignature;
  @XmlAttribute(name = "severity", required = true)
  protected int severity;

  /**
   * Gets the value of the eventSignature property.
   *
   * @return possible object is {@link String }
   */
  public String getEventSignature() {
    return eventSignature;
  }

  /**
   * Sets the value of the eventSignature property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEventSignature(String value) {
    this.eventSignature = value;
  }

  /**
   * Gets the value of the severity property.
   */
  public int getSeverity() {
    return severity;
  }

  /**
   * Sets the value of the severity property.
   */
  public void setSeverity(int value) {
    this.severity = value;
  }

}
