---
# The workflow to deploy snapshot artifact versions to GitHub packages 
# Fill free to adjust java version and additional mvn command-line parameters
# The workflow will trigger on pushes into branches different from main and release
# Please make sure that the version in the pom.xml file has the SNAPSHOT postfix

name: Maven GitHub deploy snapshot

on:
  push:
    branches-ignore:
      - "main"
      - "**release*"
      - "prettier/**"
  workflow_dispatch:
permissions:
  packages: write
  contents: read

env:
  GITHUB_GROUP: ${{ github.repository_owner }}

jobs:
  mvn-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Setup xmlstarlet"
        run: |
          sudo apt install -y xmlstarlet
      - name: "Set up JDK"
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "temurin"
          server-id: github
          server-username: GITHUB_USER
          server-password: GITHUB_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Display settings.xml
        run: cat ~/.m2/settings.xml
      - name: "Disable Maven Central Deploy"
        run: |
          xmlstarlet ed -L -d "/_:project/_:build/_:plugins/_:plugin[./_:artifactId='central-publishing-maven-plugin']" ./pom.xml

      - name: "Maven deploy"
        run: |
          mvn --batch-mode deploy -DaltDeploymentRepository=github::https://maven.pkg.github.com/${{ github.repository }} \
          -Dgpg.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: ${{ github.actor }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}